### ISSUE TITLE
Feature request binary inputs

### ISSUE THREAD

**Issue by RienduPre** [cibernox/homeassistant-poolstation#7]
Hi,
I am realy happy with the current integration you have created👏
I appreciate the work you put into it. 

I use 2 binary sensors for the water level of my pool. I saw this feature is on your todo list and hope you can find time implement this. Having this functionality I can automate some events based on high or low water level. 

Thanks in advance,

Rien

**Comment by cibernox** [comment]
@RienduPre sure, if you know a little bit of python (I know very little myself) you totally can help, adding a new sensor shouldn't be too hard. Besides, I don't have use the binary entries so it would be harder for me to test if it actually works.

**Comment by straybiker** [comment]
If am I am correct, you are using pypoolstation. Looking into that code, I don't see references to sensor input. So that would make things harder to develop. Correct?

**Comment by cibernox** [comment]
@straybiker I created pypoolstation, so we can make any change we need. The problem is that the API is not documented and I don't use the binary inputs or ORP sensor, so I don't know what field in the hundreds (literally, hundreds) of fields in the API's response to look for.

Then names are not very helpful either, these are for instance the ones I figured out that contain temperature, salt concentration, target ph and current ph:
![Screenshot 2023-06-15 at 15 05 42](https://github.com/cibernox/homeassistant-poolstation/assets/265339/8b52892b-ec47-4ea1-8b68-28eeb70a81cb)

It's mainly a matter of know where to look.

**Comment by RienduPre** [comment]
How do you get this list?

you can simply shortcut an binary input on the printboard and see if the value changes from 0 to 1

**Comment by cibernox** [comment]
This is just the requests made to the api every few seconds when you check your pool in https://poolstation.net

**Comment by RienduPre** [comment]
> This is just one of the requests made to the api every few seconds when you check your pool in https://poolstation.net

Ok but how do I execute such a request?

**Comment by RienduPre** [comment]
What I found sofar is:
THe status of the four relais:

- mc = relais1
- mj = relais2
- mb = relais3
- mf = relais4
0=off 1=on

**Comment by cibernox** [comment]
I assume you mean the binary inputs, right? Because the relays have worked for a while now.

**Comment by RienduPre** [comment]
No I'm searching for the binary inputs right now

**Comment by straybiker** [comment]
The inputs are just potential free inputs. I wired them so I can easily make the contact to test and check the api response. But it has to wait till next week.

**Comment by RienduPre** [comment]
I'm having trouble to setup a HA development environment on my M1 mac, so I'm able to do some programming myself and my python knowledge is also very limited

**Comment by cibernox** [comment]
Let me handle the pypoolstation update first to expose the binary sensors and that waterflow one too. Hopefully tonight.

For setting up HA in an M1 mac, I'd suggest to use VSCode with the docker extension installed. As soon as you open the project it should detect that it has a dockerfile and ask if you want to reopen it in a container.

**Comment by cibernox** [comment]
I've published a new version of the pypoolstation that also parses the state of the binary inputs and also their names, because they are configurable. Initially they are "D1", "D2", etc..., but in your very screenshot you've renamed one of them to "Test1". This can be useful to create the entities in home assistant with a more helpful name.
I also parsed the waterflow, which can useful to create a binary sensor with device type "problem", which is a special type of sensor that when its state is ON home assistant will report it in the UI. 
I've created one for when my heat recuperator tells me that the filters need cleaning and I found it handy.

It's a bit late to make the changes to the integration, I'll try to find time tomorrow.

**Comment by cibernox** [comment]
Update: It turns out this integration was quite outdated with modern idioms for home assistant, particularly on how number entities worked. tl;dr; Some behavior was deprecated and it would have stopped working in 2023.10. I first took care of updating and cleaning everything.

Now I think I can start adding more features. In the next few days....

**Comment by cibernox** [comment]
I added the waterflow binary sensor. It can be either OK or Problem.

Binary sensors will come next.

**Comment by RienduPre** [comment]
Works great sofar👍
Thanks for your effort.
